/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hzh.soil.view;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.hzh.soil.control.SoilCalculate;
import org.hzh.soil.model.data.SoilEntry;
import org.hzh.soil.model.dao.SoilEntryDAO;

/**
 *
 * @author Administrator
 */
public class SOIL extends javax.swing.JFrame {

    /**
     * Creates new form SOIL
     */
    public SOIL() {
        initComponents();
        this.setTitle("土壤信息系统");
        
    }

    private void showExceptions(String msg) {
        JOptionPane.showMessageDialog(null, "发生错误：\n" + msg);
    }

    private void listSoilEntries(JTable tbl, List<SoilEntry> entries) {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        for (SoilEntry se : entries) {
            model.addRow(new Object[]{se.getId(), se.getLng(), se.getLat(), se.getPh(), se.getTimestmp()});
        }
    }

    private void removeAllRowsInTable(JTable tbl) {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        int n = model.getRowCount();
        while (n-- > 0) {
            model.removeRow(n);
        }
    }

    private void transferTable(JTable src, JTable des) {
        // empty des table
        removeAllRowsInTable(des);
        DefaultTableModel model_src = (DefaultTableModel) src.getModel();
        DefaultTableModel model_des = (DefaultTableModel) des.getModel();
        int n = model_src.getRowCount();
        Vector v = model_src.getDataVector();
        for (int i = 0; i < n; i++) {
            model_des.addRow((Vector) (v.elementAt(i)));
        }
    }

    private List<SoilEntry> constFromJTable(JTable tbl) {
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        List<SoilEntry> se = new ArrayList<SoilEntry>();
        Vector vector = model.getDataVector();
        // 3rd
        for (int i = 0; i < vector.size(); i++) {
            Vector v2 = (Vector) (vector.elementAt(i));
            int id = (Integer) (v2.get(0));
            double lng = (Double) (v2.get(1));
            double lat = (Double) (v2.get(2));
            double ph = (Double) (v2.get(3));
            String tm = (String) (v2.get(4));
            se.add(new SoilEntry(id, lng, lat, ph, tm));
        }
        return se;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTextField1 = new javax.swing.JTextField();
        latTextField = new javax.swing.JTextField();
        phTextField3 = new javax.swing.JTextField();
        timestampTextField3 = new javax.swing.JTextField();
        lngTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inoutOK = new javax.swing.JButton();
        inputNO = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        filterPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filterPHmiTextField = new javax.swing.JTextField();
        filterPHmxTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        filterIdTextField = new javax.swing.JTextField();
        filterIdRead = new javax.swing.JButton();
        nofilterRead = new javax.swing.JButton();
        filterPHRead = new javax.swing.JButton();
        datashowPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filterResTbl = new javax.swing.JTable();
        toCalcPlace = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        calcDataPanel = new javax.swing.JScrollPane();
        calcDataTbl = new javax.swing.JTable();
        calcPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        statCalc = new javax.swing.JButton();
        phPowCalc = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        calcResTxt = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        help = new javax.swing.JMenu();
        about_software = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("土壤信息系统");

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setText("土壤信息输入：");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("编号：");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("经纬度：");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("Ph值：");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("录入时间：");

        idTextField1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        idTextField1.setText("101");

        latTextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        latTextField.setText("116.3917");

        phTextField3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        timestampTextField3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        lngTextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lngTextField.setText("39.9139");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("E");

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setText("N,");

        inoutOK.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        inoutOK.setText("确定");
        inoutOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inoutOKActionPerformed(evt);
            }
        });

        inputNO.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        inputNO.setText("取消");
        inputNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lngTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(latTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 152, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(inoutOK))
                            .addComponent(phTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTextField1)
                            .addComponent(timestampTextField3))
                        .addGap(18, 18, 18)
                        .addComponent(inputNO)
                        .addGap(42, 42, 42))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lngTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(latTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(timestampTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inoutOK)
                    .addComponent(inputNO))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("录入数据", jPanel2);

        jSplitPane2.setDividerLocation(80);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setOneTouchExpandable(true);

        filterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("筛选编号：");

        jLabel9.setText("筛选PH值：");

        filterPHmiTextField.setText("4.5");

        filterPHmxTextField.setText("8.5");
        filterPHmxTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterPHmxTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("--");

        filterIdTextField.setText("101");

        filterIdRead.setText("筛选");
        filterIdRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterIdReadActionPerformed(evt);
            }
        });

        nofilterRead.setText("全部读取");
        nofilterRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nofilterReadActionPerformed(evt);
            }
        });

        filterPHRead.setText("筛选");
        filterPHRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterPHReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterPHmiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterPHmxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterIdTextField)))
                .addGap(18, 18, 18)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addComponent(filterPHRead, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(nofilterRead))
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addComponent(filterIdRead, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(filterIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterIdRead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(filterPHmiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filterPHmxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterPanelLayout.createSequentialGroup()
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filterPHRead)
                            .addComponent(nofilterRead))
                        .addContainerGap())))
        );

        jSplitPane2.setTopComponent(filterPanel);

        filterResTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "编号", "经度", "纬度", "PH值", "录入时间"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        filterResTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(filterResTbl);

        toCalcPlace.setText("计算返回数据");
        toCalcPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCalcPlaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datashowPanelLayout = new javax.swing.GroupLayout(datashowPanel);
        datashowPanel.setLayout(datashowPanelLayout);
        datashowPanelLayout.setHorizontalGroup(
            datashowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datashowPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toCalcPlace)
                .addGap(26, 26, 26))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        datashowPanelLayout.setVerticalGroup(
            datashowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datashowPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(toCalcPlace)
                .addGap(21, 21, 21))
        );

        jSplitPane2.setRightComponent(datashowPanel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("读取数据", jPanel4);

        jSplitPane3.setDividerLocation(220);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane3.setOneTouchExpandable(true);

        calcDataTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "编号", "经度", "纬度", "PH值", "录入时间"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        calcDataTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        calcDataTbl.getTableHeader().setReorderingAllowed(false);
        calcDataPanel.setViewportView(calcDataTbl);

        jSplitPane3.setTopComponent(calcDataPanel);

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOneTouchExpandable(true);

        statCalc.setText("统计运算");
        statCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statCalcActionPerformed(evt);
            }
        });

        phPowCalc.setText("平方计算");
        phPowCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phPowCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phPowCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(phPowCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statCalc)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel7);

        calcResTxt.setColumns(20);
        calcResTxt.setRows(5);
        jScrollPane4.setViewportView(calcResTxt);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel8);

        javax.swing.GroupLayout calcPanelLayout = new javax.swing.GroupLayout(calcPanel);
        calcPanel.setLayout(calcPanelLayout);
        calcPanelLayout.setHorizontalGroup(
            calcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        calcPanelLayout.setVerticalGroup(
            calcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jSplitPane3.setRightComponent(calcPanel);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("数据计算", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        file.setText("文件");
        jMenuBar1.add(file);

        help.setText("帮助");

        about_software.setText("关于");
        about_software.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_softwareActionPerformed(evt);
            }
        });
        help.add(about_software);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void about_softwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_softwareActionPerformed
        JOptionPane.showMessageDialog(null, "本程序作为‘土壤信息系统’的原型系统，只用作示例。");
    }//GEN-LAST:event_about_softwareActionPerformed

    private void inoutOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inoutOKActionPerformed
        // input data to database
        try {
            int id = Integer.parseInt(idTextField1.getText());
            double lng = Double.parseDouble(lngTextField.getText());
            double lat = Double.parseDouble(latTextField.getText());
            double ph = Double.parseDouble(phTextField3.getText());
            String timestamp = timestampTextField3.getText();
            if (timestamp.length() < 1) {
                timestamp = (new java.text.SimpleDateFormat("yyyy年MM月dd日 hh:mm:ss")).format(new Date());
            }
            // c,st
            SoilEntry se = new SoilEntry(id, lng, lat, ph, timestamp);
            SoilEntryDAO dao = new SoilEntryDAO();
            dao.insertSoilEntry(se);
        } catch (Exception e) {
            showExceptions(e.toString());
        }
    }//GEN-LAST:event_inoutOKActionPerformed

    private void inputNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNOActionPerformed
        idTextField1.setText("");
        lngTextField.setText("");
        latTextField.setText("");
        phTextField3.setText("");
        timestampTextField3.setText("");
    }//GEN-LAST:event_inputNOActionPerformed

    private void filterPHmxTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterPHmxTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterPHmxTextFieldActionPerformed

    private void filterIdReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterIdReadActionPerformed
        // filter  with given id
        try {
            int id = Integer.parseInt(filterIdTextField.getText());
            SoilEntryDAO dao = new SoilEntryDAO();
            List<SoilEntry> entries = dao.selectById(id);
            // write list of results to filterResTbl
            removeAllRowsInTable(filterResTbl);
            listSoilEntries(filterResTbl, entries);

        } catch (Exception e) {
            showExceptions(e.toString());
        }

    }//GEN-LAST:event_filterIdReadActionPerformed

    private void nofilterReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nofilterReadActionPerformed
        // filter  with given id
        try {
            SoilEntryDAO dao = new SoilEntryDAO();
            List<SoilEntry> entries = dao.selectAll();
            // write list of results to filterResTbl
            removeAllRowsInTable(filterResTbl);
            listSoilEntries(filterResTbl, entries);

        } catch (Exception e) {
            showExceptions(e.toString());
        }
    }//GEN-LAST:event_nofilterReadActionPerformed

    private void filterPHReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterPHReadActionPerformed
        try {
            double phmin = Double.parseDouble(filterPHmiTextField.getText());
            double phmax = Double.parseDouble(filterPHmxTextField.getText());
            if (phmin > phmax) {
                showExceptions("PH范围设置错误");
            }
            SoilEntryDAO dao = new SoilEntryDAO();
            List<SoilEntry> entries = dao.selectPhRange(phmin, phmax);
            removeAllRowsInTable(filterResTbl);
            listSoilEntries(filterResTbl, entries);

        } catch (Exception e) {
            showExceptions(e.toString());
        }
    }//GEN-LAST:event_filterPHReadActionPerformed

    private void toCalcPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCalcPlaceActionPerformed
        // TODO add your handling code here:
        transferTable(filterResTbl, calcDataTbl);
        jTabbedPane1.setSelectedIndex(2);
        // transfer data to calculate panel

    }//GEN-LAST:event_toCalcPlaceActionPerformed

    private void phPowCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phPowCalcActionPerformed
        List<SoilEntry> se = constFromJTable(calcDataTbl);
        SoilCalculate sc = new SoilCalculate(se);
        List<Double> pow_ph = sc.pow2Ph();
        StringBuilder sb = new StringBuilder();
        for (double d : pow_ph) {
            sb.append(d + "\n");
        }
        calcResTxt.setText(sb.toString());
    }//GEN-LAST:event_phPowCalcActionPerformed

    private void statCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statCalcActionPerformed
        List<SoilEntry> se = constFromJTable(calcDataTbl);
        SoilCalculate sc = new SoilCalculate(se);
        StringBuilder sb = new StringBuilder();
        sb.append("平均值：" + sc.avgPh() + "\n");
        sb.append("标准偏差：" + sc.stdDev() + "\n其它...");
        calcResTxt.setText(sb.toString());
    }//GEN-LAST:event_statCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SOIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SOIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SOIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SOIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SOIL().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about_software;
    private javax.swing.JScrollPane calcDataPanel;
    private javax.swing.JTable calcDataTbl;
    private javax.swing.JPanel calcPanel;
    private javax.swing.JTextArea calcResTxt;
    private javax.swing.JPanel datashowPanel;
    private javax.swing.JMenu file;
    private javax.swing.JButton filterIdRead;
    private javax.swing.JTextField filterIdTextField;
    private javax.swing.JButton filterPHRead;
    private javax.swing.JTextField filterPHmiTextField;
    private javax.swing.JTextField filterPHmxTextField;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JTable filterResTbl;
    private javax.swing.JMenu help;
    private javax.swing.JTextField idTextField1;
    private javax.swing.JButton inoutOK;
    private javax.swing.JButton inputNO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField latTextField;
    private javax.swing.JTextField lngTextField;
    private javax.swing.JButton nofilterRead;
    private javax.swing.JButton phPowCalc;
    private javax.swing.JTextField phTextField3;
    private javax.swing.JButton statCalc;
    private javax.swing.JTextField timestampTextField3;
    private javax.swing.JButton toCalcPlace;
    // End of variables declaration//GEN-END:variables
}
